### ISSUE TITLE
scroll to bottom should be already scrolled to the bottom the first time it renders

### ISSUE THREAD

**Issue by pritipsingh** [stackblitz/use-stick-to-bottom#10]
is it possible that the messages container to start already scrolled to the bottom the first time it renders (and avoid visually scrolling from top to bottom) ? can we add something like initial="none"

**Comment by samdenty** [comment]
initial="instant"

**Comment by williamlmao** [comment]
Hi @samdenty, I cannot get initial="instant" to work no matter what I try - here's a minimal reproducible example in v0: https://v0.app/chat/ai-chat-app-rBG8YEfRBHg?ref=A8BXOZ

You can see in this example it will still start from the top and smooth scroll down on load

**Comment by williamlmao** [comment]
Opened an issue here: https://github.com/stackblitz-labs/use-stick-to-bottom/issues/29
