### ISSUE TITLE
[feature request] hide scrollbar

### ISSUE THREAD

**Issue by fourcolors** [stackblitz/use-stick-to-bottom#6]
it would be nice to be able to easily hide scrollbar. This could be as simple as being able to set style on the scroll element for additional customization

**Comment by samdenty** [comment]
you can add custom classnames/inline styles to customize the scrollbar appearance. Also the `overflow` property is also only added when there's no existing style on the element.

https://github.com/stackblitz/use-stick-to-bottom/blob/cf0f46a4779f052c587250259ceb12af221cb5fb/src/StickToBottom.tsx#L71 

I think this styles on the scrollRef or the StickToBottom component should do the trick:

```ts
.container {
    -ms-overflow-style: none;  /* Internet Explorer 10+ */
    scrollbar-width: none;  /* Firefox */
}
.container::-webkit-scrollbar { 
    display: none;  /* Safari and Chrome */
}
```

this library is only concerned with handling smooth scrolling, styling is out of the question so i'll close this issue. Hopefully the above helps you
